var constants = {
    VIEW_WIDTH: 800,
    VIEW_HEIGHT: 600,
    BLOCK_IMAGE: "./img/block.png",
    BLOCK_SIZE: 16,
    PLAYGROUND_HEIGHT: 20,
    PLAYGROUND_WIDTH: 10,
    PLAYGROUND_BORDER: 2,
    PLAYGROUND_BORDER_COLOR: 0x0088FF,
    KEY_UP: 38,
    KEY_DOWN: 40,
    KEY_LEFT: 37,
    KEY_RIGHT: 39
};